add middleware exceptions
jpsandovaln/JU-CONVERTER pull request #27
Opened 2022-11-01 16:19 UTC by MauricioAliendre182

Middleware Exception Added

2022-11-01 20:41 UTC, HugoS922 commented on spring-boot-hello-world/src/main/java/com/jalasoft/convert/middleware/AudioControllerMiddleware.java
>  import javax.servlet.*;
Hello Mauricio there are still Imports with "*", please try to remove them with the correct imports

2022-11-01 20:42 UTC, HugoS922 commented on spring-boot-hello-world/src/main/java/com/jalasoft/convert/middleware/DocControllerMiddleware.java
>  import javax.servlet.FilterChain;
Same here Mauricio

2022-11-01 20:43 UTC, HugoS922 commented on Download/Traducido-File.txt
> +﻿
Hello Mauricio this is an unnecesary file, for the PR you should remove it, please try to revove it before merging

2022-11-01 20:46 UTC, HugoS922 requested changes
Hello @MauricioAliendre182 there are at least 6 imprts with "*", please try to remove them, and the TXT file that is not used

2022-11-02 17:40 UTC, MauricioAliendre182 commented
> Hello @MauricioAliendre182 there are at least 6 imports with "*", please try to remove them, and the TXT file that is not used

Ok Hugo, I will do it, I will upload middleware exceptions in this PR too

2022-11-02 17:54 UTC, closed without merging